# Generated by Django 4.0.6 on 2022-07-17 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_address', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('active_power', models.FloatField()),
                ('apparent_power', models.FloatField()),
                ('active_energy', models.FloatField()),
                ('apparent_energy', models.FloatField()),
                ('phase_current', models.FloatField()),
                ('neutral_current', models.FloatField()),
                ('frequency', models.FloatField()),
                ('power_factor', models.FloatField()),
                ('meter_time', models.DateTimeField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_meter', to='app.meter')),
            ],
        ),
    ]
