version: "3.8"
   
services:
  db:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gram-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hrhk
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/main
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=localhost
      - DB_NAME=gram-db
      - DB_USER=postgres
      - DB_PASS=hrhk
    depends_on:
      - db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A main worker -l info
    depends_on:
      - db
      - redis
      - web